### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by kojix2** [jiquan/Dataset-acess-for-PLOS-ONE#1]
Hello. jiquan.

Thank you for publishing your awesome datasets.
What is the license for this dataset?

**Comment by jiquan** [comment]
I have revised README to include license policy, and thanks for your commit.

**Comment by kojix2** [comment]
Thank you for your clarification. 

Today, many people are developing diagnostic software for endoscopes all around the world. However, it is difficult to disclose medical images because they are personal information. There's also the question of who will get the revenue from the software. Company? Hospital? Doctor? Patient?

A few years ago, I was a little involved in a project to create diagnostic software for endoscopes, but I didn't like the fact that it was too enterprise-centric and lacked openness.

Ideally, I think the diagnostic software for endoscopes should be open source and preferably open data.

I forked the repository and tried keras-yolo3 (just for fun)
https://github.com/kojix2/Gastric-polyps-detection

Thank you for your great effort again.
